---
- name: appsettings.json
  become: true
  template: 
    src: appsettings.json.j2
    dest: '/var/www/{{ container_name }}/appsettings.json'
    owner: root
    group: root
    mode: '0600'

- name: Docker container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: ghcr.io/evanlihou/tracker:latest
    state: started
    recreate: true
    pull: true
    restart_policy: unless-stopped
    published_ports:
      - '127.0.0.1:{{ web_port }}:80'
    volumes:
      - '/var/www/{{ container_name }}/appsettings.json:/app/appsettings.json:ro'
    env:
      DOTNET_URLS: 'http://+'

- name: Caddy config
  become: true
  ansible.builtin.blockinfile:
    backup: true
    path: '/etc/caddy/Caddyfile'
    block: "{{ lookup('template', 'Caddyfile_part.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK ({{ container_name }})"