---
container_name: matomo
web_port: 8060
hostname: a7s.evandoes.dev
database_host: "{{ lookup('community.general.onepassword', 'matomo', field='database_host', vault='Personal Servers') | string }}"
database_username: "{{ lookup('community.general.onepassword', 'matomo', field='database_username', vault='Personal Servers') | string }}"
database_password: "{{ lookup('community.general.onepassword', 'matomo', field='database_password', vault='Personal Servers') | string }}"
database_dbname: "{{ lookup('community.general.onepassword', 'matomo', field='database_dbname', vault='Personal Servers') | string }}"
